[project]
name = "render"
version = "0.1.0"
description = "Render infrastrcture and configuration files"
readme = "README.md"
license = "LICENSE"
requires-python = ">=3.14,<3.15"
dependencies = [
    "ansible-vault>=2.1.0",
    "jinja2>=3.1.6",
    "pyyaml>=6.0.3",
    "cffi>=2.0.0",
]
